<?php

namespace Izzai\One\Types;

/**
 * NOTE: THIS FILE WAS GENERATED BY MONGOOSE-TSGEN AND CONVERTED TO PHP.
 * ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.
 */

// ######################################## TYPE DEFINITIONS ######################################## //

/**
 * Lean version of TagDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Tag
{
  /** @var string */
  public $label;
  /** @var string|null */
  public $color;
  /** @var ('avatar'|'chat')[] */
  public $categories;
  /** @var string[]|null */
  public $users;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

/**
 * Lean version of AgentDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Agent
{
  /** @var string */
  public $name;
  /** @var (string|AgentStep)[] */
  public $steps;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var mixed */
  public $access;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

/**
 * Lean version of AgentStepLlmCapabilityDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class AgentStepLlmCapability
{
  /** @var bool|null */
  public $chat;
  /** @var bool|null */
  public $embedding;
  /** @var bool|null */
  public $function;
  /** @var bool|null */
  public $speech;
  /** @var bool|null */
  public $realTimeSpeech;
  /** @var bool|null */
  public $vision;
}

/**
 * Lean version of AgentStepLlmDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class AgentStepLlm
{
  /** @var string|null */
  public $key;
  /** @var string|null */
  public $label;
  /** @var string|null */
  public $engine;
  /** @var AgentStepLlmCapability|null */
  public $capabilities;
  /** @var string|null */
  public $description;
  /** @var string|null */
  public $uuid;
  /** @var ('azure'|'huggingface'|'ollama'|'anthropic'|'openai'|'perplexity')|null */
  public $provider;
}

/**
 * Lean version of AgentStepDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class AgentStep
{
  /** @var string */
  public $name;
  /** @var ('userMessage'|'outputParser'|'tool'|'systemMessage'|'gpt'|'datasource') */
  public $type;
  /** @var ('SystemMessage'|'Gpt'|'Datasource')|null */
  public $refPath;
  /** @var string|null */
  public $content;
  /** @var AgentStepLlm|null */
  public $llm;
  /** @var ('jsonApi'|'websiteMarkdown'|'websiteHtml')|null */
  public $tool;
  /** @var string|null */
  public $ref;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of ChatLlmCapabilityDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class ChatLlmCapability
{
  /** @var bool|null */
  public $chat;
  /** @var bool|null */
  public $embedding;
  /** @var bool|null */
  public $function;
  /** @var bool|null */
  public $speech;
  /** @var bool|null */
  public $realTimeSpeech;
  /** @var bool|null */
  public $vision;
}

/**
 * Lean version of ChatLlmDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class ChatLlm
{
  /** @var string|null */
  public $key;
  /** @var string|null */
  public $label;
  /** @var string|null */
  public $engine;
  /** @var ChatLlmCapability|null */
  public $capabilities;
  /** @var string|null */
  public $description;
  /** @var string|null */
  public $uuid;
  /** @var ('azure'|'huggingface'|'ollama'|'anthropic'|'openai'|'perplexity')|null */
  public $provider;
}

/**
 * Lean version of ChatDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Chat
{
  /** @var string */
  public $user;
  /** @var string|null */
  public $label;
  /** @var string|null */
  public $summary;
  /** @var int|null */
  public $tokenLimit;
  /** @var int|null */
  public $token;
  /** @var int|null */
  public $totalToken;
  /** @var string|null */
  public $messageId;
  /** @var string|null */
  public $status;
  /** @var ChatLlm|null */
  public $llm;
  /** @var string|Agent|null */
  public $agent;
  /** @var (string|Datasource)[]|null */
  public $datasources;
  /** @var string|Gpt|null */
  public $gpt;
  /** @var string|null */
  public $outputParser;
  /** @var ('JSON'|'MARKDOWN'|'TEXT'|'SPEECH')|null */
  public $outputFormat;
  /** @var ('conversational'|'explaining'|'creative'|'formal'|'informal'|'technical'|'friendly'|'professional'|'humorous')[] */
  public $behavior;
  /** @var (string|Tag)[]|null */
  public $tags;
  /** @var bool|null */
  public $useInternet;
  /** @var bool|null */
  public $excludeReferences;
  /** @var string|null */
  public $systemMessage;
  /** @var bool|null */
  public $imageChat;
  /** @var bool|null */
  public $isFavourite;
  /** @var string|null */
  public $favouriteDate;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var mixed|null */
  public $llmOptions;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of DatasourceTokensPerMinuteDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceTokensPerMinute
{
  /** @var int|null */
  public $count;
  /** @var int|null */
  public $internalCount;
  /** @var string|null */
  public $lastReset;
}

/**
 * Lean version of DatasourceBlobStorageDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceBlobStorage
{
  /** @var string */
  public $connectionString;
  /** @var string */
  public $containerName;
  /** @var string|null */
  public $accessID;
  /** @var string|null */
  public $secret;
  /** @var string|null */
  public $region;
  /** @var ('azure'|'s3')|null */
  public $type;
  /** @var int|null */
  public $successCount;
  /** @var int|null */
  public $replacedCount;
  /** @var int|null */
  public $skippedCount;
  /** @var int|null */
  public $totalCount;
  /** @var float|null */
  public $completionPercentage;
}

/**
 * Lean version of DatasourceBraveSearchDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceBraveSearch
{
  /** @var string */
  public $apiKey;
}

/**
 * Lean version of DatasourceClickupDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceClickup
{
  /** @var string */
  public $apiKey;
  /** @var string */
  public $teamId;
  /** @var bool|null */
  public $documentSupport;
}

/**
 * Lean version of DatasourceCognitiveSearchDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceCognitiveSearch
{
  /** @var string */
  public $endpoint;
  /** @var string */
  public $indexerName;
  /** @var string */
  public $indexName;
  /** @var string */
  public $apiKey;
}

/**
 * Lean version of DatasourceMssqlDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceMssql
{
  /** @var string */
  public $host;
  /** @var string|null */
  public $user;
  /** @var string|null */
  public $password;
  /** @var string */
  public $database;
  /** @var int|null */
  public $port;
  /** @var string|null */
  public $schemaPath;
  /** @var string[] */
  public $schemaFiles;
}

/**
 * Lean version of DatasourceMysqlDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceMysql
{
  /** @var string */
  public $host;
  /** @var string|null */
  public $user;
  /** @var string|null */
  public $password;
  /** @var string */
  public $database;
  /** @var int|null */
  public $port;
  /** @var string|null */
  public $schemaPath;
  /** @var string[] */
  public $schemaFiles;
}

/**
 * Lean version of DatasourceMongodbDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceMongodb
{
  /** @var string */
  public $host;
  /** @var string|null */
  public $user;
  /** @var string|null */
  public $password;
  /** @var string */
  public $database;
  /** @var int|null */
  public $port;
  /** @var string|null */
  public $schemaPath;
  /** @var string[] */
  public $schemaFiles;
  /** @var bool|null */
  public $srv;
}

/**
 * Lean version of DatasourceCosmosdbDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceCosmosdb
{
  /** @var string */
  public $host;
  /** @var string|null */
  public $user;
  /** @var string|null */
  public $password;
  /** @var string */
  public $database;
  /** @var int|null */
  public $port;
  /** @var string|null */
  public $schemaPath;
  /** @var string[] */
  public $schemaFiles;
}

/**
 * Lean version of DatasourcePostgreDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourcePostgre
{
  /** @var string */
  public $host;
  /** @var string|null */
  public $user;
  /** @var string|null */
  public $password;
  /** @var string */
  public $database;
  /** @var int|null */
  public $port;
  /** @var string|null */
  public $schemaPath;
  /** @var string[] */
  public $schemaFiles;
}

/**
 * Lean version of DatasourceElasticSearchDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceElasticSearch
{
  /** @var string */
  public $endpoint;
  /** @var string */
  public $indexName;
  /** @var string|null */
  public $username;
  /** @var string|null */
  public $password;
  /** @var string|null */
  public $apiKey;
}

/**
 * Lean version of DatasourceEmailAuthDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceEmailAuth
{
  /** @var string|null */
  public $type;
  /** @var string */
  public $user;
  /** @var string|null */
  public $pass;
  /** @var string|null */
  public $clientId;
  /** @var string|null */
  public $clientSecret;
  /** @var string|null */
  public $refreshToken;
}

/**
 * Lean version of DatasourceEmailDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceEmail
{
  /** @var string|null */
  public $service;
  /** @var string */
  public $host;
  /** @var int */
  public $port;
  /** @var bool|null */
  public $secure;
  /** @var DatasourceEmailAuth|null */
  public $auth;
}

/**
 * Lean version of DatasourceGenericMcpDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceGenericMcp
{
  /** @var string */
  public $url;
  /** @var mixed|null */
  public $requestInit;
  /** @var string|null */
  public $toolNamePrefix;
  /** @var string|null */
  public $clientName;
  /** @var string|null */
  public $clientVersion;
}

/**
 * Lean version of DatasourceGithubDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceGithub
{
  /** @var string */
  public $apiKey;
  /** @var bool|null */
  public $readOnly;
}

/**
 * Lean version of DatasourceGoogleProgrammableSearchDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceGoogleProgrammableSearch
{
  /** @var string */
  public $apiKey;
  /** @var string */
  public $cx;
}

/**
 * Lean version of DatasourceNotionDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceNotion
{
  /** @var string */
  public $authToken;
}

/**
 * Lean version of DatasourceSerpApiDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceSerpApi
{
  /** @var string */
  public $apiKey;
}

/**
 * Lean version of DatasourceSlackDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceSlack
{
  /** @var string */
  public $botToken;
  /** @var string */
  public $teamId;
  /** @var string[]|null */
  public $channelIds;
}

/**
 * Lean version of DatasourceShopifyDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceShopify
{
  /** @var string */
  public $accessToken;
  /** @var string */
  public $domain;
}

/**
 * Lean version of DatasourceZenserpDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class DatasourceZenserp
{
  /** @var string */
  public $apiKey;
}

/**
 * Lean version of DatasourceDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Datasource
{
  /** @var string|null */
  public $indexName;
  /** @var int|null */
  public $indexSize;
  /** @var string|null */
  public $displayName;
  /** @var bool|null */
  public $immutable;
  /** @var ('mssql'|'mysql'|'mongodb'|'cosmosdb'|'postgres'|'semanticIndex'|'cognitiveSearch'|'blobStorage'|'elasticSearch'|'fetch'|'slack'|'clickup'|'email'|'genericMcp'|'notion'|'github'|'shopify'|'braveSearch'|'googleProgrammableSearch'|'serpApi'|'zenserp'|'auto')|null */
  public $type;
  /** @var ('failed'|'indexing'|'pending'|'ready')|null */
  public $status;
  /** @var bool|null */
  public $isActive;
  /** @var bool|null */
  public $isValid;
  /** @var bool|null */
  public $isInitialized;
  /** @var string|null */
  public $initDate;
  /** @var string|null */
  public $reInitDate;
  /** @var string|null */
  public $failedInitialize;
  /** @var int|null */
  public $chunkSize;
  /** @var int|null */
  public $chunkOverlap;
  /** @var ('semantic'|'manual')|null */
  public $indexMode;
  /** @var int|null */
  public $tokensUsed;
  /** @var int|null */
  public $internalTokensUsed;
  /** @var bool|null */
  public $isMerged;
  /** @var DatasourceTokensPerMinute|null */
  public $tokensPerMinute;
  /** @var string|Storage|null */
  public $storage;
  /** @var float|null */
  public $percent;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string|null */
  public $description;
  /** @var int|null */
  public $failureCount;
  /** @var mixed */
  public $access;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
  /** @var DatasourceBlobStorage|null */
  public $blobStorage;
  /** @var DatasourceBraveSearch|null */
  public $braveSearch;
  /** @var DatasourceClickup|null */
  public $clickup;
  /** @var DatasourceCognitiveSearch|null */
  public $cognitiveSearch;
  /** @var DatasourceMssql|null */
  public $mssql;
  /** @var DatasourceMysql|null */
  public $mysql;
  /** @var DatasourceMongodb|null */
  public $mongodb;
  /** @var DatasourceCosmosdb|null */
  public $cosmosdb;
  /** @var DatasourcePostgre|null */
  public $postgres;
  /** @var DatasourceElasticSearch|null */
  public $elasticSearch;
  /** @var DatasourceEmail|null */
  public $email;
  /** @var mixed|null */
  public $fetch;
  /** @var DatasourceGenericMcp|null */
  public $genericMcp;
  /** @var DatasourceGithub|null */
  public $github;
  /** @var DatasourceGoogleProgrammableSearch|null */
  public $googleProgrammableSearch;
  /** @var DatasourceNotion|null */
  public $notion;
  /** @var DatasourceSerpApi|null */
  public $serpApi;
  /** @var DatasourceSlack|null */
  public $slack;
  /** @var DatasourceShopify|null */
  public $shopify;
  /** @var DatasourceZenserp|null */
  public $zenserp;
}

// ---

/**
 * Lean version of GptLlmCapabilityDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class GptLlmCapability
{
  /** @var bool|null */
  public $chat;
  /** @var bool|null */
  public $embedding;
  /** @var bool|null */
  public $function;
  /** @var bool|null */
  public $speech;
  /** @var bool|null */
  public $realTimeSpeech;
  /** @var bool|null */
  public $vision;
}

/**
 * Lean version of GptLlmDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class GptLlm
{
  /** @var string|null */
  public $key;
  /** @var string|null */
  public $label;
  /** @var string|null */
  public $engine;
  /** @var GptLlmCapability|null */
  public $capabilities;
  /** @var string|null */
  public $description;
  /** @var string|null */
  public $uuid;
  /** @var ('azure'|'huggingface'|'ollama'|'anthropic'|'openai'|'perplexity')|null */
  public $provider;
}

/**
 * Lean version of GptDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Gpt
{
  /** @var string */
  public $user;
  /** @var string[] */
  public $access;
  /** @var string */
  public $name;
  /** @var string|null */
  public $description;
  /** @var GptLlm|null */
  public $llm;
  /** @var ('active'|'draft'|'inactive')|null */
  public $status;
  /** @var string|Datasource|null */
  public $datasource;
  /** @var ('JSON'|'MARKDOWN'|'TEXT'|'SPEECH')|null */
  public $outputFormat;
  /** @var string|null */
  public $outputParser;
  /** @var ('conversational'|'explaining'|'creative'|'formal'|'informal'|'technical'|'friendly'|'professional'|'humorous')[] */
  public $behavior;
  /** @var bool|null */
  public $useInternet;
  /** @var string|null */
  public $systemMessage;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var mixed|null */
  public $llmOptions;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of MessageFileContentDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class MessageFileContent
{
  /** @var string|null */
  public $file;
  /** @var string|null */
  public $content;
}

/**
 * Lean version of MessageScratchPadDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class MessageScratchPad
{
  /** @var string|null */
  public $time;
  /** @var mixed|null */
  public $output;
  /** @var string|null */
  public $input;
  /** @var string|null */
  public $reason;
}

/**
 * Lean version of MessageLlmCapabilityDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class MessageLlmCapability
{
  /** @var bool|null */
  public $chat;
  /** @var bool|null */
  public $embedding;
  /** @var bool|null */
  public $function;
  /** @var bool|null */
  public $speech;
  /** @var bool|null */
  public $realTimeSpeech;
  /** @var bool|null */
  public $vision;
}

/**
 * Lean version of MessageLlmDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class MessageLlm
{
  /** @var string|null */
  public $key;
  /** @var string|null */
  public $label;
  /** @var string|null */
  public $engine;
  /** @var MessageLlmCapability|null */
  public $capabilities;
  /** @var string|null */
  public $description;
  /** @var string|null */
  public $uuid;
  /** @var ('azure'|'huggingface'|'ollama'|'anthropic'|'openai'|'perplexity')|null */
  public $provider;
}

/**
 * Lean version of MessageDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Message
{
  /** @var string */
  public $user;
  /** @var string|Chat|null */
  public $chat;
  /** @var string|null */
  public $date;
  /** @var string|null */
  public $content;
  /** @var MessageFileContent[] */
  public $fileContent;
  /** @var mixed|null */
  public $parsedContent;
  /** @var ('function'|'assistant'|'user'|'system'|'tool')|null */
  public $role;
  /** @var ('JSON'|'MARKDOWN'|'TEXT'|'SPEECH')|null */
  public $outputFormat;
  /** @var (string|Message)[]|null */
  public $related;
  /** @var bool|null */
  public $activeVariant;
  /** @var mixed|null */
  public $outputParser;
  /** @var mixed|null */
  public $rawResponse;
  /** @var string[] */
  public $filePaths;
  /** @var int|null */
  public $token;
  /** @var bool|null */
  public $summarized;
  /** @var bool|null */
  public $isPinned;
  /** @var string|null */
  public $pinnedDate;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string|null */
  public $image;
  /** @var bool|null */
  public $isCustom;
  /** @var bool|null */
  public $isSpeech;
  /** @var MessageScratchPad[] */
  public $scratchPad;
  /** @var MessageLlm|null */
  public $llm;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of ResourceAccessDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class ResourceAccess
{
  /** @var string */
  public $user;
  /** @var ('datasource'|'agent')|null */
  public $type;
  /** @var bool|null */
  public $read;
  /** @var bool|null */
  public $update;
  /** @var bool|null */
  public $delete;
  /** @var string|Datasource|null */
  public $datasource;
  /** @var string|Agent|null */
  public $agent;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of StorageAzureDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class StorageAzure
{
  /** @var string */
  public $connectionString;
  /** @var string */
  public $containerName;
}

/**
 * Lean version of StorageS3Document
 *
 * This has all Mongoose getters & functions removed.
 */
class StorageS3
{
  /** @var string */
  public $accessID;
  /** @var string */
  public $secret;
  /** @var string */
  public $bucketName;
  /** @var string */
  public $region;
}

/**
 * Lean version of StorageDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Storage
{
  /** @var string */
  public $displayName;
  /** @var ('azure'|'s3') */
  public $type;
  /** @var StorageAzure|null */
  public $azure;
  /** @var StorageS3|null */
  public $s3;
  /** @var bool|null */
  public $immutable;
  /** @var bool|null */
  public $isInitialized;
  /** @var string|null */
  public $failedInitialize;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of SystemMessageDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class SystemMessage
{
  /** @var string|null */
  public $user;
  /** @var string */
  public $content;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of TokenUsageDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class TokenUsage
{
  /** @var ('datasource')|null */
  public $type;
  /** @var int|null */
  public $tokens;
  /** @var int|null */
  public $internalTokens;
  /** @var string|Datasource|null */
  public $datasource;
  /** @var string|null */
  public $startAt;
  /** @var string|null */
  public $endAt;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}

// ---

/**
 * Lean version of TrainingPropertyDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class TrainingProperty
{
  /** @var string|null */
  public $lastModified;
  /** @var string|null */
  public $etag;
  /** @var int|null */
  public $contentLength;
}

/**
 * Lean version of TrainingDocument
 *
 * This has all Mongoose getters & functions removed.
 */
class Training
{
  /** @var string|null */
  public $path;
  /** @var string[]|null */
  public $urls;
  /** @var string[]|null */
  public $excludes;
  /** @var bool|null */
  public $excludeHash;
  /** @var bool|null */
  public $isRecursive;
  /** @var ('website'|'file')|null */
  public $type;
  /** @var string|null */
  public $mimeType;
  /** @var ('url'|'initiated'|'pending'|'uploaded'|'training'|'trained'|'removed'|'untraining'|'untrained'|'failed')|null */
  public $status;
  /** @var string|null */
  public $failureReason;
  /** @var string|Datasource|null */
  public $datasource;
  /** @var string|null */
  public $originalFileName;
  /** @var string[] */
  public $fileNames;
  /** @var string */
  public $addedBy;
  /** @var bool|null */
  public $isArchived;
  /** @var string|null */
  public $archiveDate;
  /** @var string|Training|null */
  public $parent;
  /** @var string[] */
  public $vectorIds;
  /** @var string|Storage|null */
  public $storage;
  /** @var mixed|null */
  public $meta;
  /** @var float|null */
  public $percent;
  /** @var ('reset'|'append')|null */
  public $mode;
  /** @var TrainingProperty|null */
  public $properties;
  /** @var string */
  public $_id;
  /** @var string|null */
  public $createdAt;
  /** @var string|null */
  public $updatedAt;
}
